# Generated by Django 5.0 on 2024-02-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudes', '0004_category_algorithm_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='algo_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
            ],
        ),
    ]
