# Generated by Django 5.0 on 2024-02-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitudes', '0005_algo_category_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
